username = "dsjfksldjf"
password = "automation1"

[base_urls]
flipkart = "https://www.flipkart.com/"
facebook = "https://www.facebook.com/"
harman_connect_services = "https://services.harman.com/"
amazon = "https://www.amazon.in/"
make_my_trip = "https://www.makemytrip.com/"
demo_web_shop = "https://demowebshop.tricentis.com/"
instahyre = "https://www.instahyre.com/"


