username = "dsjfksldjf"
password = "automation1"

[base_urls]
flipkart = "https://www.flipkart.com/"
facebook = "https://www.facebook.com/"
harman_connect_services = "https://services.harman.com/"
amazon = "https://www.amazon.in/"
saucedemo = "https://www.saucedemo.com/v1/"
google= "https://www.google.com/"
make_my_trip = "https://www.makemytrip.com/"
